In [1]:
import pandas as pd
import numpy as np

### Read the csv file

In [2]:
df = pd.read_csv('mexico_covid19.csv')
df

,id,FECHA_ARCHIVO,ID_REGISTRO,ENTIDAD_UM,ENTIDAD_RES,RESULTADO,DELAY,ENTIDAD_REGISTRO,ENTIDAD,ABR_ENT,...,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

In [3]:
df.columns

Index(['id', 'FECHA_ARCHIVO', 'ID_REGISTRO', 'ENTIDAD_UM', 'ENTIDAD_RES',
       'RESULTADO', 'DELAY', 'ENTIDAD_REGISTRO', 'ENTIDAD', 'ABR_ENT',
       'FECHA_ACTUALIZACION', 'ORIGEN', 'SECTOR', 'SEXO', 'ENTIDAD_NAC',
       'MUNICIPIO_RES', 'TIPO_PACIENTE', 'FECHA_INGRESO', 'FECHA_SINTOMAS',
       'FECHA_DEF', 'INTUBADO', 'NEUMONIA', 'EDAD', 'NACIONALIDAD', 'EMBARAZO',
       'HABLA_LENGUA_INDIG', 'DIABETES', 'EPOC', 'ASMA', 'INMUSUPR',
       'HIPERTENSION', 'OTRA_COM', 'CARDIOVASCULAR', 'OBESIDAD',
       'RENAL_CRONICA', 'TABAQUISMO', 'OTRO_CASO', 'MIGRANTE',
       'PAIS_NACIONALIDAD', 'PAIS_ORIGEN', 'UCI'],
      dtype='object')

### Column Renaming of Dataframe

In [4]:
df.rename(columns = {'FECHA_ARCHIVO':'Date_Archive', 'ID_REGISTRO':'Registration_Id', 'ENTIDAD_UM':'ENTITY_UM', 'ENTIDAD_RES':'ENTITY_RES',
       'RESULTADO':'OUTCOME',  'ENTIDAD_REGISTRO':'REGISTRATION_ENTITY', 'ENTIDAD':'ENTITY', 'ABR_ENT':'APR ENT',
       'FECHA_ACTUALIZACION':'DATE_UPDATE', 'ORIGEN':'SOURCE', 'SECTOR':'SECTOR', 'SEXO':'SEX', 'ENTIDAD_NAC':'NAC_ENTITY',
       'MUNICIPIO_RES':'MUNICIPALITY_RES', 'TIPO_PACIENTE':'PATIENT TYPE', 'FECHA_INGRESO':'ADMISSION DATE', 'FECHA_SINTOMAS':'DATE SYMPTOMS',
       'FECHA_DEF':'DATE DEF', 'INTUBADO':'INTUBATED', 'NEUMONIA':'PNEUMONIA', 'EDAD':'AGE', 'NACIONALIDAD':'NATIONALITY', 'EMBARAZO':'PREGNANCY',
       'HABLA_LENGUA_INDIG':'SPEAKS_INDIG_LANGUAGE', 'DIABETES':'DIABETES', 'EPOC':'COPD', 'ASMA':'ASTHMA', 'INMUSUPR':'INMUSUPR',
       'HIPERTENSION':'HYPERTENSION', 'OTRA_COM':'ANOTHER COM', 'CARDIOVASCULAR':'CARDIOVASCULAR', 'OBESIDAD':'OBESITY',
       'RENAL_CRONICA':'KIDNEY CHRONICLE', 'TABAQUISMO':'SMOKING', 'OTRO_CASO':'ANOTHER CASE', 'MIGRANTE':'MIGRANT',
       'PAIS_NACIONALIDAD':'COUNTRY NATIONALITY', 'PAIS_ORIGEN':'COUNTRY OF ORIGIN', 'UCI':'ICU'},inplace=True)

In [5]:
df

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

### Count NAN value in the dataframe

In [6]:
df.isna().values.any()

True

In [7]:
df.isnull().sum()            # df.isna().sum()

id                       0
Date_Archive             0
Registration_Id          0
ENTITY_UM                0
ENTITY_RES               0
OUTCOME                  0
DELAY                    0
REGISTRATION_ENTITY      0
ENTITY                   0
APR ENT                  0
DATE_UPDATE              0
SOURCE                   0
SECTOR                   0
SEX                      0
NAC_ENTITY               0
MUNICIPALITY_RES         6
PATIENT TYPE             0
ADMISSION DATE           0
DATE SYMPTOMS            0
DATE DEF                 0
INTUBATED                0
PNEUMONIA                0
AGE                      0
NATIONALITY              0
PREGNANCY                0
SPEAKS_INDIG_LANGUAGE    0
DIABETES                 0
COPD                     0
ASTHMA                   0
INMUSUPR                 0
HYPERTENSION             0
ANOTHER COM              0
CARDIOVASCULAR           0
OBESITY                  0
KIDNEY CHRONICLE         0
SMOKING                  0
ANOTHER CASE             0
MIGRANT                  0
COUNTRY NATIONALITY      0
COUNTRY OF ORIGIN        0
ICU                      0
dtype: int64

In [8]:
df.isin([np.inf,-np.inf]).sum()

id                       0
Date_Archive             0
Registration_Id          0
ENTITY_UM                0
ENTITY_RES               0
OUTCOME                  0
DELAY                    0
REGISTRATION_ENTITY      0
ENTITY                   0
APR ENT                  0
DATE_UPDATE              0
SOURCE                   0
SECTOR                   0
SEX                      0
NAC_ENTITY               0
MUNICIPALITY_RES         0
PATIENT TYPE             0
ADMISSION DATE           0
DATE SYMPTOMS            0
DATE DEF                 0
INTUBATED                0
PNEUMONIA                0
AGE                      0
NATIONALITY              0
PREGNANCY                0
SPEAKS_INDIG_LANGUAGE    0
DIABETES                 0
COPD                     0
ASTHMA                   0
INMUSUPR                 0
HYPERTENSION             0
ANOTHER COM              0
CARDIOVASCULAR           0
OBESITY                  0
KIDNEY CHRONICLE         0
SMOKING                  0
ANOTHER CASE             0
MIGRANT                  0
COUNTRY NATIONALITY      0
COUNTRY OF ORIGIN        0
ICU                      0
dtype: int64

### Total NAN value in the entire dataframe

In [9]:
df.isnull().sum().sum()               # df.isna().sum().sum()

6

In [10]:
df.isin([np.inf,-np.inf]).sum().sum()

0

In [11]:
df.shape

(263007, 41)

In [12]:
df.columns

Index(['id', 'Date_Archive', 'Registration_Id', 'ENTITY_UM', 'ENTITY_RES',
       'OUTCOME', 'DELAY', 'REGISTRATION_ENTITY', 'ENTITY', 'APR ENT',
       'DATE_UPDATE', 'SOURCE', 'SECTOR', 'SEX', 'NAC_ENTITY',
       'MUNICIPALITY_RES', 'PATIENT TYPE', 'ADMISSION DATE', 'DATE SYMPTOMS',
       'DATE DEF', 'INTUBATED', 'PNEUMONIA', 'AGE', 'NATIONALITY', 'PREGNANCY',
       'SPEAKS_INDIG_LANGUAGE', 'DIABETES', 'COPD', 'ASTHMA', 'INMUSUPR',
       'HYPERTENSION', 'ANOTHER COM', 'CARDIOVASCULAR', 'OBESITY',
       'KIDNEY CHRONICLE', 'SMOKING', 'ANOTHER CASE', 'MIGRANT',
       'COUNTRY NATIONALITY', 'COUNTRY OF ORIGIN', 'ICU'],
      dtype='object')

### Print hidden columns

In [13]:
df[['DATE_UPDATE', 'SOURCE', 'SECTOR', 'SEX', 'NAC_ENTITY',
       'MUNICIPALITY_RES', 'PATIENT TYPE', 'ADMISSION DATE', 'DATE SYMPTOMS',
       'DATE DEF', 'INTUBATED', 'PNEUMONIA', 'AGE', 'NATIONALITY', 'PREGNANCY',
       'SPEAKS_INDIG_LANGUAGE']]

,DATE_UPDATE,SOURCE,SECTOR,SEX,NAC_ENTITY,MUNICIPALITY_RES,PATIENT TYPE,ADMISSION DATE,DATE SYMPTOMS,DATE DEF,INTUBATED,PNEUMONIA,AGE,NATIONALITY,PREGNANCY,SPEAKS_INDIG_LANGUAGE
0,2020-04-19,2,12,2,25,13.0,1,2020-03-20,2020-03-12,9999-99-99,97,2,74,1,97,2
1,2020-04-19,1,4,1,16,98.0,2,2020-03-30,2020-03-30,9999-99-99,2,2,71,1,2,2
2,2020-04-19,1,4,2,8,19.0,2,2020-04-02,2020-03-24,9999-99-99,2,1,50,1,97,2
3,2020-04-19,2,4,1,15,33.0,1,2020-04-01,2020-03-26,9999-99-99,97,2,25,1,2,2
4,2020-04-19,1,4,1,99,15.0,1,2020-04-07,2020-04-06,9999-99-99,97,2,28,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,2020-06-03,2,12,2,32,53.0,1,2020-06-03,2020-06-01,9999-99-99,97,2,39,1,97,2
263003,2020-06-03,2,4,1,12,35.0,2,2020-04-24,2020-04-24,2020-05-07,2,1,53,1,2,2
263004,2020-06-03,1,4,1,20,390.0,2,2020-05-14,2020-05-11,2020-05-18,2,2,65,1,2,2
263005,2020-06-03,2,12,2,20,51.0,2,2020-06-02,2020-05-28,9999-99-99,2,1,71,1,97,2
263006,2020-06-03,2,12,1,9,6.0,1,2020-05-04,2020-05-04,9999-99-99,97,2,18,1,2,2

In [14]:
df[['DIABETES', 'COPD', 'ASTHMA', 'INMUSUPR',
       'HYPERTENSION']]

        DIABETES  COPD  ASTHMA  INMUSUPR  HYPERTENSION
0              1     2       2         2             1
1              1     1       2         2             1
2              2     2       2         2             2
3              2     2       2         2             2
4              2     2       2         2             2
...          ...   ...     ...       ...           ...
263002         2     2       2         2             2
263003         1     1       2         2             2
263004         1     2       2         2             1
263005         2     2       2         2             1
263006         2     2       2         2             2

[263007 rows x 5 columns]

### Max Values of each column

In [15]:
df.count()

id                       263007
Date_Archive             263007
Registration_Id          263007
ENTITY_UM                263007
ENTITY_RES               263007
OUTCOME                  263007
DELAY                    263007
REGISTRATION_ENTITY      263007
ENTITY                   263007
APR ENT                  263007
DATE_UPDATE              263007
SOURCE                   263007
SECTOR                   263007
SEX                      263007
NAC_ENTITY               263007
MUNICIPALITY_RES         263001
PATIENT TYPE             263007
ADMISSION DATE           263007
DATE SYMPTOMS            263007
DATE DEF                 263007
INTUBATED                263007
PNEUMONIA                263007
AGE                      263007
NATIONALITY              263007
PREGNANCY                263007
SPEAKS_INDIG_LANGUAGE    263007
DIABETES                 263007
COPD                     263007
ASTHMA                   263007
INMUSUPR                 263007
HYPERTENSION             263007
ANOTHER COM              263007
CARDIOVASCULAR           263007
OBESITY                  263007
KIDNEY CHRONICLE         263007
SMOKING                  263007
ANOTHER CASE             263007
MIGRANT                  263007
COUNTRY NATIONALITY      263007
COUNTRY OF ORIGIN        263007
ICU                      263007
dtype: int64

In [16]:
df.max(axis = 0)

id                            7277125
Date_Archive               2020-06-03
Registration_Id                z3d1e2
ENTITY_UM                          32
ENTITY_RES                         32
OUTCOME                             2
DELAY                               0
REGISTRATION_ENTITY                32
ENTITY                      Zacatecas
APR ENT                            ZS
DATE_UPDATE                2020-06-03
SOURCE                              2
SECTOR                             99
SEX                                 2
NAC_ENTITY                         99
MUNICIPALITY_RES                  999
PATIENT TYPE                        2
ADMISSION DATE             2020-06-03
DATE SYMPTOMS              2020-06-02
DATE DEF                   9999-99-99
INTUBATED                          99
PNEUMONIA                          99
AGE                               120
NATIONALITY                         2
PREGNANCY                          98
SPEAKS_INDIG_LANGUAGE              99
DIABETES                           98
COPD                               98
ASTHMA                             98
INMUSUPR                           98
HYPERTENSION                       98
ANOTHER COM                        98
CARDIOVASCULAR                     98
OBESITY                            98
KIDNEY CHRONICLE                   98
SMOKING                            98
ANOTHER CASE                       99
MIGRANT                            99
COUNTRY NATIONALITY      Zona Neutral
COUNTRY OF ORIGIN           Venezuela
ICU                                99
dtype: object

In [17]:
df[['ENTITY_UM','ENTITY_RES','OUTCOME','DELAY','REGISTRATION_ENTITY','NAC_ENTITY','MUNICIPALITY_RES','PATIENT TYPE','INTUBATED', 'PNEUMONIA', 'AGE', 'PREGNANCY','DIABETES', 'COPD', 'ASTHMA', 'INMUSUPR',
       'HYPERTENSION','CARDIOVASCULAR', 'OBESITY',
       'KIDNEY CHRONICLE', 'SMOKING', 'ANOTHER CASE', 'MIGRANT','ICU']].max()

ENTITY_UM               32.0
ENTITY_RES              32.0
OUTCOME                  2.0
DELAY                    0.0
REGISTRATION_ENTITY     32.0
NAC_ENTITY              99.0
MUNICIPALITY_RES       999.0
PATIENT TYPE             2.0
INTUBATED               99.0
PNEUMONIA               99.0
AGE                    120.0
PREGNANCY               98.0
DIABETES                98.0
COPD                    98.0
ASTHMA                  98.0
INMUSUPR                98.0
HYPERTENSION            98.0
CARDIOVASCULAR          98.0
OBESITY                 98.0
KIDNEY CHRONICLE        98.0
SMOKING                 98.0
ANOTHER CASE            99.0
MIGRANT                 99.0
ICU                     99.0
dtype: float64

### Min value of each column

In [18]:
df[['ENTITY_UM','ENTITY_RES','OUTCOME','DELAY','REGISTRATION_ENTITY','NAC_ENTITY','MUNICIPALITY_RES','PATIENT TYPE','INTUBATED', 'PNEUMONIA', 'AGE', 'PREGNANCY','DIABETES', 'COPD', 'ASTHMA', 'INMUSUPR',
       'HYPERTENSION','CARDIOVASCULAR', 'OBESITY',
       'KIDNEY CHRONICLE', 'SMOKING', 'ANOTHER CASE', 'MIGRANT','ICU']].min()

ENTITY_UM              1.0
ENTITY_RES             1.0
OUTCOME                1.0
DELAY                  0.0
REGISTRATION_ENTITY    1.0
NAC_ENTITY             1.0
MUNICIPALITY_RES       1.0
PATIENT TYPE           1.0
INTUBATED              1.0
PNEUMONIA              1.0
AGE                    0.0
PREGNANCY              1.0
DIABETES               1.0
COPD                   1.0
ASTHMA                 1.0
INMUSUPR               1.0
HYPERTENSION           1.0
CARDIOVASCULAR         1.0
OBESITY                1.0
KIDNEY CHRONICLE       1.0
SMOKING                1.0
ANOTHER CASE           1.0
MIGRANT                1.0
ICU                    1.0
dtype: float64

### Mean value of each column

In [19]:
df[['ENTITY_UM','ENTITY_RES','OUTCOME','DELAY','REGISTRATION_ENTITY','NAC_ENTITY','MUNICIPALITY_RES','PATIENT TYPE','INTUBATED', 'PNEUMONIA', 'AGE', 'PREGNANCY','DIABETES', 'COPD', 'ASTHMA', 'INMUSUPR',
       'HYPERTENSION','CARDIOVASCULAR', 'OBESITY',
       'KIDNEY CHRONICLE', 'SMOKING', 'ANOTHER CASE', 'MIGRANT','ICU']].mean()

ENTITY_UM              14.844601
ENTITY_RES             15.127719
OUTCOME                 1.609672
DELAY                   0.000000
REGISTRATION_ENTITY    15.092271
NAC_ENTITY             19.691004
MUNICIPALITY_RES       36.441401
PATIENT TYPE            1.236378
INTUBATED              74.543362
PNEUMONIA               1.842993
AGE                    42.591627
PREGNANCY              50.708825
DIABETES                2.239712
COPD                    2.320102
ASTHMA                  2.300711
INMUSUPR                2.359667
HYPERTENSION            2.174185
CARDIOVASCULAR          2.324980
OBESITY                 2.184763
KIDNEY CHRONICLE        2.320231
SMOKING                 2.268217
ANOTHER CASE           32.283764
MIGRANT                98.593680
ICU                    74.541012
dtype: float64

### Standard deviation of each column

In [20]:
df[['ENTITY_UM','ENTITY_RES','OUTCOME','DELAY','REGISTRATION_ENTITY','NAC_ENTITY','MUNICIPALITY_RES','PATIENT TYPE','INTUBATED', 'PNEUMONIA', 'AGE', 'PREGNANCY','DIABETES', 'COPD', 'ASTHMA', 'INMUSUPR',
       'HYPERTENSION','CARDIOVASCULAR', 'OBESITY',
       'KIDNEY CHRONICLE', 'SMOKING', 'ANOTHER CASE', 'MIGRANT','ICU']].std()

ENTITY_UM               8.001043
ENTITY_RES              7.904314
OUTCOME                 0.487825
DELAY                   0.000000
REGISTRATION_ENTITY     7.915406
NAC_ENTITY             19.378113
MUNICIPALITY_RES       48.117024
PATIENT TYPE            0.424858
INTUBATED              40.379846
PNEUMONIA               0.798979
AGE                    16.903824
PREGNANCY              47.494775
DIABETES                5.958047
COPD                    5.704424
ASTHMA                  5.682309
INMUSUPR                6.021830
HYPERTENSION            5.745114
CARDIOVASCULAR          5.796086
OBESITY                 5.817362
KIDNEY CHRONICLE        5.722995
SMOKING                 5.867586
ANOTHER CASE           45.350310
MIGRANT                 6.275497
ICU                    40.384991
dtype: float64

### Variance of each column

In [21]:
df[['ENTITY_UM','ENTITY_RES','OUTCOME','DELAY','REGISTRATION_ENTITY','NAC_ENTITY','MUNICIPALITY_RES','PATIENT TYPE','INTUBATED', 'PNEUMONIA', 'AGE', 'PREGNANCY','DIABETES', 'COPD', 'ASTHMA', 'INMUSUPR',
       'HYPERTENSION','CARDIOVASCULAR', 'OBESITY',
       'KIDNEY CHRONICLE', 'SMOKING', 'ANOTHER CASE', 'MIGRANT','ICU']].var()

ENTITY_UM                64.016690
ENTITY_RES               62.478175
OUTCOME                   0.237973
DELAY                     0.000000
REGISTRATION_ENTITY      62.653646
NAC_ENTITY              375.511253
MUNICIPALITY_RES       2315.248004
PATIENT TYPE              0.180504
INTUBATED              1630.531947
PNEUMONIA                 0.638368
AGE                     285.739282
PREGNANCY              2255.753643
DIABETES                 35.498327
COPD                     32.540451
ASTHMA                   32.288633
INMUSUPR                 36.262436
HYPERTENSION             33.006335
CARDIOVASCULAR           33.594607
OBESITY                  33.841706
KIDNEY CHRONICLE         32.752676
SMOKING                  34.428569
ANOTHER CASE           2056.650586
MIGRANT                  39.381861
ICU                    1630.947497
dtype: float64

In [22]:
df.var(axis = 1)

0         2.760205e+06
1         3.580947e+07
2         4.058205e+07
3         1.601730e+06
4         1.815869e+07
              ...
263002    1.623778e+12
263003    1.604994e+12
263004    1.605765e+12
263005    1.600467e+12
263006    1.623045e+12
Length: 263007, dtype: float64

In [23]:
df.describe()                            # for statistics of dataset

,id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,SOURCE,SECTOR,SEX,NAC_ENTITY,...,INMUSUPR,HYPERTENSION,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,ICU
count,2.630070e+05,263007.000000,263007.000000,263007.000000,263007.0,263007.000000,263007.000000,263007.000000,263007.000000,263007.000000,...,263007.000000,263007.000000,263007.000000,263007.000000,263007.000000,263007.000000,263007.000000,263007.000000,263007.000000,263007.000000
mean,2.946176e+06,14.844601,15.127719,1.609672,0.0,15.092271,1.635789,9.601680,1.510682,19.691004,...,2.359667,2.174185,2.453961,2.324980,2.184763,2.320231,2.268217,32.283764,98.593680,74.541012
std,2.212368e+06,8.001043,7.904314,0.487825,0.0,7.915406,0.481209,7.265468,0.499887,19.378113,...,6.021830,5.745114,6.850231,5.796086,5.817362,5.722995,5.867586,45.350310,6.275497,40.384991
min,1.000000e+00,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,8.689635e+05,9.000000,9.000000,1.000000,0.0,9.000000,1.000000,4.000000,1.000000,9.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,99.000000,97.000000
50%,2.733242e+06,14.000000,15.000000,2.000000,0.0,15.000000,2.000000,12.000000,2.000000,15.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,99.000000,97.000000
75%,4.789668e+06,21.000000,21.000000,2.000000,0.0,21.000000,2.000000,12.000000,2.000000,24.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,99.000000,99.000000,97.000000
max,7.277125e+06,32.000000,32.000000,2.000000,0.0,32.000000,2.000000,99.000000,2.000000,99.000000,...,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,99.000000,99.000000,99.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263007 entries, 0 to 263006
Data columns (total 41 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     263007 non-null  int64
 1   Date_Archive           263007 non-null  object
 2   Registration_Id        263007 non-null  object
 3   ENTITY_UM              263007 non-null  int64
 4   ENTITY_RES             263007 non-null  int64
 5   OUTCOME                263007 non-null  int64
 6   DELAY                  263007 non-null  int64
 7   REGISTRATION_ENTITY    263007 non-null  int64
 8   ENTITY                 263007 non-null  object
 9   APR ENT                263007 non-null  object
 10  DATE_UPDATE            263007 non-null  object
 11  SOURCE                 263007 non-null  int64
 12  SECTOR                 263007 non-null  int64
 13  SEX                    263007 non-null  int64
 14  NAC_ENTITY             263007 non-null  int64
 15  MUNICIPALITY_RES       263001 non-null  float64
 16  PATIENT TYPE           263007 non-null  int64
 17  ADMISSION DATE         263007 non-null  object
 18  DATE SYMPTOMS          263007 non-null  object
 19  DATE DEF               263007 non-null  object
 20  INTUBATED              263007 non-null  int64
 21  PNEUMONIA              263007 non-null  int64
 22  AGE                    263007 non-null  int64
 23  NATIONALITY            263007 non-null  int64
 24  PREGNANCY              263007 non-null  int64
 25  SPEAKS_INDIG_LANGUAGE  263007 non-null  int64
 26  DIABETES               263007 non-null  int64
 27  COPD                   263007 non-null  int64
 28  ASTHMA                 263007 non-null  int64
 29  INMUSUPR               263007 non-null  int64
 30  HYPERTENSION           263007 non-null  int64
 31  ANOTHER COM            263007 non-null  int64
 32  CARDIOVASCULAR         263007 non-null  int64
 33  OBESITY                263007 non-null  int64
 34  KIDNEY CHRONICLE       263007 non-null  int64
 35  SMOKING                263007 non-null  int64
 36  ANOTHER CASE           263007 non-null  int64
 37  MIGRANT                263007 non-null  int64
 38  COUNTRY NATIONALITY    263007 non-null  object
 39  COUNTRY OF ORIGIN      263007 non-null  object
 40  ICU                    263007 non-null  int64
dtypes: float64(1), int64(30), object(10)
memory usage: 82.3+ MB

### Replace inf by nan value

In [25]:
inf_replace = df.replace([np.inf,-np.inf],np.NaN)

In [26]:
drop_nan = df.dropna()
drop_nan

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

In [27]:
df

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

### Indexing and Slicing in dataframe

In [28]:
df.head()

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97

In [29]:
df.head(20)

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
5,5019,2020-04-12,0001d2,19,19,2,0,19,Nuevo Leon,NL,...,2,2,1,2,1,99,99,MÃ©xico,97,97
6,30173,2020-04-12,0001e7,17,17,2,0,17,Morelos,MS,...,2,2,1,2,1,99,99,MÃ©xico,97,97
7,26574,2020-04-12,00022b,27,27,2,0,27,Tabasco,TC,...,2,2,1,2,2,1,99,MÃ©xico,97,97
8,4265,2020-04-12,000275,19,19,2,0,19,Nuevo Leon,NL,...,2,2,2,2,2,99,99,MÃ©xico,97,97
9,25444,2020-04-12,0002e7,15,15,2,0,15,Mexico,MC,...,2,2,2,2,2,2,99,MÃ©xico,97,97
10,12204,2020-04-12,0002ec,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
11,3321,2020-04-12,0002f5,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,1,2,99,99,97,97
12,17950,2020-04-12,00032c,5,5,2,0,5,Coahuila,CL,...,2,2,2,2,2,99,99,MÃ©xico,97,97
13,24675,2020-04-12,00032f,19,19,2,0,19,Nuevo Leon,NL,...,1,2,2,2,2,99,99,MÃ©xico,97,2
14,8225,2020-04-12,00037e,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
15,9723,2020-04-12,0003fb,28,28,2,0,28,Tamaulipas,TS,...,2,2,2,2,2,1,99,MÃ©xico,97,97
16,13159,2020-04-12,0005b4,11,11,2,0,11,Guanajuato,GT,...,2,2,2,2,2,99,99,99,97,97
17,29753,2020-04-12,0005d5,24,24,2,0,24,San Luis Potosi,SP,...,2,2,2,2,2,99,99,MÃ©xico,97,97
18,13779,2020-04-12,0005e5,15,9,1,0,15,Mexico,MC,...,2,2,2,2,2,99,99,MÃ©xico,97,97
19,865,2020-04-12,0005fa,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,97,97

In [30]:
df.tail()

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

In [31]:
df.tail(30)

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
262977,7082214,2020-06-03,1ce339,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,1,99,MÃ©xico,99,97
262978,7247711,2020-06-03,1ce4c1,1,1,2,0,1,Aguascalientes,AS,...,2,2,2,2,1,2,99,MÃ©xico,99,97
262979,7112380,2020-06-03,1cf39a,16,16,1,0,16,Michoacan,MN,...,2,2,1,2,1,99,99,MÃ©xico,99,2
262980,7049289,2020-06-03,1cf798,27,27,1,0,27,Tabasco,TC,...,2,2,2,2,2,99,99,MÃ©xico,99,2
262981,7088286,2020-06-03,1d1273,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262982,7054908,2020-06-03,1d2886,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,99,2
262983,7244991,2020-06-03,1d2e14,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262984,7050226,2020-06-03,1d32f7,18,18,1,0,18,Nayarit,NT,...,2,1,2,2,2,99,99,MÃ©xico,99,2
262985,7037017,2020-06-03,1d4443,27,27,1,0,27,Tabasco,TC,...,2,2,2,2,2,99,99,MÃ©xico,99,2
262986,7094315,2020-06-03,1d49db,15,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262987,7180877,2020-06-03,1d4f81,1,1,2,0,1,Aguascalientes,AS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262988,7186229,2020-06-03,1d6169,1,1,2,0,1,Aguascalientes,AS,...,2,2,2,2,2,2,99,MÃ©xico,99,97
262989,7101413,2020-06-03,1d6d65,14,14,1,0,14,Jalisco,JC,...,2,2,2,2,2,99,99,MÃ©xico,99,97
262990,7041964,2020-06-03,1d705b,27,27,1,0,27,Tabasco,TC,...,2,2,2,2,2,99,99,MÃ©xico,99,2
262991,7070914,2020-06-03,1d7e52,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,1,99,MÃ©xico,99,97
262992,7050828,2020-06-03,1d9dd2,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262993,7087659,2020-06-03,1dae40,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97
262994,7054898,2020-06-03,1db56a,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262995,7211408,2020-06-03,1db672,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,99,97
262996,7043441,2020-06-03,1dbaaa,20,20,1,0,20,Oaxaca,OC,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262997,7094652,2020-06-03,1dd338,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,99,2
262998,7229955,2020-06-03,1de0f3,27,27,2,0,27,Tabasco,TC,...,2,2,2,2,2,99,99,MÃ©xico,99,2
262999,7077068,2020-06-03,1ded44,31,31,1,0,31,Yucatan,YN,...,2,2,2,2,2,99,99,MÃ©xico,99,97
263000,7165176,2020-06-03,1df427,18,18,2,0,18,Nayarit,NT,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263001,7034532,2020-06-03,1df812,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

In [32]:
df[25:200]

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
25,4443,2020-04-12,00086c,15,15,2,0,15,Mexico,MC,...,2,2,2,2,2,99,99,MÃ©xico,97,97
26,16861,2020-04-12,000892,2,2,2,0,2,Baja California,BC,...,2,2,2,2,2,99,99,MÃ©xico,97,97
27,29816,2020-04-12,00093c,21,21,2,0,21,Puebla,PL,...,2,2,2,2,2,1,99,MÃ©xico,97,97
28,5687,2020-04-12,000947,32,32,2,0,32,Zacatecas,ZS,...,1,2,2,2,2,1,99,MÃ©xico,97,97
29,30050,2020-04-12,00096a,13,13,2,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,97,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27132,2020-04-12,003d84,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,99,97,97
196,15098,2020-04-12,003e2b,22,22,2,0,22,Queretaro,QT,...,2,2,2,2,2,2,99,MÃ©xico,97,97
197,9169,2020-04-12,003e61,32,32,2,0,32,Zacatecas,ZS,...,2,1,2,2,2,99,99,MÃ©xico,97,97
198,12479,2020-04-12,003eb7,30,30,2,0,30,Veracruz,VZ,...,2,2,2,1,2,99,99,MÃ©xico,97,2
199,21756,2020-04-12,003f5e,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,97,97

In [33]:
df[262500:]

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
262500,7178957,2020-06-03,1e00f2,27,27,2,0,27,Tabasco,TC,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262501,7164329,2020-06-03,1e055b,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262502,7205194,2020-06-03,1e0790,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97
262503,7060081,2020-06-03,1e14c0,28,28,1,0,28,Tamaulipas,TS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
262504,7247589,2020-06-03,1e1c8f,10,10,2,0,10,Durango,DG,...,2,2,2,2,2,2,99,MÃ©xico,99,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

### Droping multiple rows

In [34]:
df.head()

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97

In [35]:
drop_row = df.drop([0,3,5,6],axis=0)              # drop row0 & row3
drop_row

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
7,26574,2020-04-12,00022b,27,27,2,0,27,Tabasco,TC,...,2,2,1,2,2,1,99,MÃ©xico,97,97
8,4265,2020-04-12,000275,19,19,2,0,19,Nuevo Leon,NL,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

### Drop Specific Multiple Columns

In [36]:
drop_col = df.drop(['DELAY', 'REGISTRATION_ENTITY', 'ENTITY', 'APR ENT'],axis =1)
drop_col

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DATE_UPDATE,SOURCE,SECTOR,SEX,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,2020-04-19,2,12,2,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,2020-04-19,1,4,1,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,2020-04-19,1,4,2,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,2020-04-19,2,4,1,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,2020-04-19,1,4,1,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,2020-06-03,2,12,2,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,2020-06-03,2,4,1,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,2020-06-03,1,4,1,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,2020-06-03,2,12,2,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,2020-06-03,2,12,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97

### Remove column based on column index

In [37]:
df

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

In [38]:
drop_Col = df.drop(df.columns[[0,2,3,5]],axis = 1)
drop_Col

,Date_Archive,ENTITY_RES,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,DATE_UPDATE,SOURCE,SECTOR,SEX,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,2020-04-12,25,0,25,Sinaloa,SL,2020-04-19,2,12,2,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,2020-04-12,14,0,14,Jalisco,JC,2020-04-19,1,4,1,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,2020-04-12,8,0,8,Chihuahua,CH,2020-04-19,1,4,2,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,2020-04-12,15,0,9,Ciudad de Mexico,DF,2020-04-19,2,4,1,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,2020-04-12,9,0,9,Ciudad de Mexico,DF,2020-04-19,1,4,1,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,2020-06-03,32,0,32,Zacatecas,ZS,2020-06-03,2,12,2,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,2020-06-03,12,0,12,Guerrero,GR,2020-06-03,2,4,1,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,2020-06-03,20,0,20,Oaxaca,OC,2020-06-03,1,4,1,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,2020-06-03,13,0,13,Hidalgo,HG,2020-06-03,2,12,2,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,2020-06-03,9,0,9,Ciudad de Mexico,DF,2020-06-03,2,12,1,...,2,2,2,2,2,2,99,MÃ©xico,99,97

### Remove all columns between a specific column to another

#### Drop columns from a Dataframe using iloc[] and drop() method

In [39]:
df

,id,Date_Archive,Registration_Id,ENTITY_UM,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,25,2,0,25,Sinaloa,SL,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,14,2,0,14,Jalisco,JC,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,8,1,0,8,Chihuahua,CH,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,15,1,0,9,Ciudad de Mexico,DF,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,9,2,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,32,1,0,32,Zacatecas,ZS,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,12,1,0,12,Guerrero,GR,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,20,1,0,20,Oaxaca,OC,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,13,1,0,13,Hidalgo,HG,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,9,1,0,9,Ciudad de Mexico,DF,...,2,2,2,2,2,2,99,MÃ©xico,99,97

In [40]:
drop_colmn = df.drop(df.iloc[:, 1:4] ,axis = 1)
drop_colmn

,id,ENTITY_RES,OUTCOME,DELAY,REGISTRATION_ENTITY,ENTITY,APR ENT,DATE_UPDATE,SOURCE,SECTOR,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,25,2,0,25,Sinaloa,SL,2020-04-19,2,12,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,14,2,0,14,Jalisco,JC,2020-04-19,1,4,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,8,1,0,8,Chihuahua,CH,2020-04-19,1,4,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,15,1,0,9,Ciudad de Mexico,DF,2020-04-19,2,4,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,9,2,0,9,Ciudad de Mexico,DF,2020-04-19,1,4,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,32,1,0,32,Zacatecas,ZS,2020-06-03,2,12,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,12,1,0,12,Guerrero,GR,2020-06-03,2,4,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,20,1,0,20,Oaxaca,OC,2020-06-03,1,4,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,13,1,0,13,Hidalgo,HG,2020-06-03,2,12,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,9,1,0,9,Ciudad de Mexico,DF,2020-06-03,2,12,...,2,2,2,2,2,2,99,MÃ©xico,99,97

#### Drop columns from a Dataframe using loc[] and drop() method

In [42]:
drop_colmn = df.drop(df.loc[:, 'ENTITY_RES':'ENTITY'].columns ,axis = 1)
drop_colmn

,id,Date_Archive,Registration_Id,ENTITY_UM,APR ENT,DATE_UPDATE,SOURCE,SECTOR,SEX,NAC_ENTITY,...,ANOTHER COM,CARDIOVASCULAR,OBESITY,KIDNEY CHRONICLE,SMOKING,ANOTHER CASE,MIGRANT,COUNTRY NATIONALITY,COUNTRY OF ORIGIN,ICU
0,9269,2020-04-12,00011f,25,SL,2020-04-19,2,12,2,25,...,2,2,1,2,2,2,99,MÃ©xico,97,97
1,33333,2020-04-12,00014e,14,JC,2020-04-19,1,4,1,16,...,2,2,1,2,1,99,99,MÃ©xico,97,2
2,35483,2020-04-12,000153,8,CH,2020-04-19,1,4,2,8,...,2,2,2,2,2,99,99,MÃ©xico,97,2
3,7062,2020-04-12,0001b6,9,DF,2020-04-19,2,4,1,15,...,2,2,1,2,2,99,99,MÃ©xico,97,97
4,23745,2020-04-12,0001c1,9,DF,2020-04-19,1,4,1,99,...,2,2,2,2,2,99,99,MÃ©xico,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263002,7094887,2020-06-03,1e019c,32,ZS,2020-06-03,2,12,2,32,...,2,2,2,2,2,1,99,MÃ©xico,99,97
263003,7053721,2020-06-03,1e2b05,12,GR,2020-06-03,2,4,1,12,...,2,2,1,2,2,99,99,MÃ©xico,99,2
263004,7055429,2020-06-03,1e473f,20,OC,2020-06-03,1,4,1,20,...,2,2,2,1,2,99,99,MÃ©xico,99,2
263005,7043768,2020-06-03,1e6da1,13,HG,2020-06-03,2,12,2,20,...,2,2,2,2,2,2,99,MÃ©xico,99,2
263006,7093277,2020-06-03,1e8453,9,DF,2020-06-03,2,12,1,9,...,2,2,2,2,2,2,99,MÃ©xico,99,97

#### [NOTE: Difference between loc() & iloc() is iloc() exclude last column range element ]